# Send prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# Use All-arrow keys to switch panes
bind -n M-h select-pane -L
bind -n M-t select-pane -D
bind -n M-n select-pane -U
bind -n M-s select-pane -R

# Shift arrow to switch windows
bind -n M-H previous-window
bind -n M-S next-window

# Set easier window split keys
bind-key z split-window -h
bind-key v split-window -v

# Kill session or window
bind -n M-w kill-pane
bind -n M-W kill-window

# Resize pane
bind -r H resize-pane -L 5
bind -r T resize-pane -D 5
bind -r N resize-pane -U 5
bind -r S resize-pane -R 5

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
